<?php

namespace Database\Seeders;

use App\Models\Admin;
use Illuminate\Database\Seeder;

class AdminSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Admin::updateOrCreate(
            ['id' => 1], [
                'name' => 'admin',
                'email' => 'admin@admin.admin',
                'password' => bcrypt('123'), // 123 generated by bcrypt algorithm
            ]);
    }
}
