<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        if (DB::table('users')->count() == 0) {
            User::create([
                'name' => 'user',
                'email' => 'user@user.user',
                'password' =>
                '$2y$10$mb0rNw2GlNGWP66WdHpP0OELkKgVAbZQC33QqP6cctaUOtVX5fjSm', // 123 generated by bcrypt algorithm
            ]);
        }

    }
}